name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install MeCab
      run: |
        sudo apt install -y mecab libmecab-dev mecab-ipadic-utf8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8, mypy
      run: |
        flake8 --ignore E501 rhyme.py
        mypy rhyme.py
    - name: Test with unittest
      run: |
        python test_rhyme.py
